### ISSUE TITLE
Script crashing

### ISSUE THREAD

**Issue by Anonymousdog** [bdalpe/RADIUS-to-Okta-MFA#33]
I tried to switch this over to using as many system modules as possible on Ubuntu 20.04 and somehow broke it. It had been running with a pure pip3 user site install. At any rate, when run, it looks fine until an actual request is sent. At that point, the script throws the following output:
`2021-11-09 19:11:30,325 [INFO    ] Starting server on port 1812...
2021-11-09 19:11:40,381 [INFO    ] Received an authentication request for akinnard@klcpas.com.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 33, in auth_handler
    "Proxy-State": pkt["Proxy-State"]
  File "/home/akinnard/.local/lib/python3.8/site-packages/pyrad/packet.py", line 330, in __getitem__
    values = OrderedDict.__getitem__(self, self._EncodeKey(key))
KeyError: 33
`
Any insight you may have would be appreciated.

**Comment by Anonymousdog** [comment]
Nvrmnd, this was my testing with a standard RADIUS test client (instead of NPS)
